### ISSUE TITLE
Travis not deploying to pip

### ISSUE THREAD

**Issue by SR4ven** [jtpereyda/boofuzz#254]
With the recent changes to the travis config, the deployment to pip seems to be broken.
I will take a look at this as soon as I can.

**Comment by SR4ven** [comment]
So I took a brief look at it and it seems to be an issue with the `branch = master` condition.
Looking at the travis log, the branch it is cloning is `v0.1.4`
```
git clone --depth=50 --branch=v0.1.4 https://github.com/jtpereyda/boofuzz.git jtpereyda/boofuzz
```
I have no idea why this worked with the previous deploy contion like this:
```YAML
  on:
    tags: true
    repo: jtpereyda/boofuzz
    branch: master
```
If the idea behind this condition was to only deploy if a GitHub tag is present and the commit is not coming from a fork, maybe this would do it:
```YAML
stages:
  - Test
  - name: Deploy
    if: (repo = jtpereyda/boofuzz) AND (fork = false) AND (tag IS present)
```
Sadly this is hard to test and I don't really know how to fix this for the current release. Maybe just manually deploy it.
